version: '3'

services:
  app:
    container_name: webshippy_app
    environment:
      - APACHE_RUN_USER=#1000
    build:
      context: ./
    ports:
      - 80:80
    volumes:
      - ./../:/var/www/html